# ! coop_assembly
# branches:
#   only:
#   - dev
#   except:
#   - dev

language: python

python:
  - "3.6"

before_install:
  - git submodule update --init --recursive
  - pip install Cython --install-option="--no-cython-compile"
install:
  - pip install cmake
  - pip install ./external/compas_fab
  - pip install ./external/pybullet_planning
  # TODO: building FD can be tricky on Windows, need to do it from VS2017 Developer command prompt
#   - python ./external/pddlstream/FastDownward/build.py
  # TODO: if testing pyplanner, need to export its path to env: `PYPLANNER_PATH`
  - pip install --no-cache-dir -r requirements-dev.txt

script:
# The new coverage version has some breaking changes and is not backwards
# compatible. See z4r/python-coveralls#73
  - pip install coverage==4.5.4
  - pip install python-coveralls
  - invoke test
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      invoke docs;
    fi

after_success:
  - coveralls
